[package]
name = "swiftide-docker-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
swiftide-core = "0.16.0"

bollard = "0.18"
thiserror = "2.0"
async-trait = "0.1"
ignore = "0.4"
tokio = { version = "1", default-features = false }
tokio-tar = "0.3"
uuid = { version = "1.11", features = ["v4"] }
tracing = "0.1.41"
indoc = "2.0.5"
anyhow = "1.0.95"

[dev-dependencies]
test-log = "0.2.16"
tempfile = "3.15.0"
